employee/employee_mgmt/employee_mgmt/urls.py
from django.conf.urls import *
from django.contrib import admin
# from django.urls import path  
from empapp import views  


urlpatterns = [
    # Examples:
    # url(r'^$', 'employee_mgmt.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url('emp', views.emp),  
    url('show',views.show),  
    url(r'^edit/(?P<id>\d+)/?$', views.edit),  
    url(r'^update/(?P<id>\d+)/?$', views.update),  
    url(r'^delete/(?P<id>\d+)/?$', views.destroy),  
]

employee/employee_mgmt/empapp/models.py
from django.db import models
class Employee(models.Model):
    eid = models.CharField(max_length=20, primary_key=True)
    won = models.ForeignKey(
        'WonDetails',
        on_delete=models.CASCADE,
    )
    ename = models.CharField(max_length=100)
    status = models.CharField(max_length=15)
    start_date = models.DateField(max_length=15, default=None)
    end_date = models.DateField(max_length=15, default=None)
    class Meta:
        db_table = "employee"
class WonDetails(models.Model):
    won_no = models.IntegerField(primary_key=True)
    won_name = models.CharField(max_length=100)
    class Meta:
        db_table = "won_details"

employee/employee_mgmt/empapp/forms.py
#
from django import forms  
from empapp.models import Employee  
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"  

employee/employee_mgmt/empapp/views.py
from django.shortcuts import render, redirect  
from datetime import datetime
from empapp.forms import EmployeeForm  
from empapp.models import Employee , WonDetails
# Create your views here.  
def emp(request):  
    if request.method == "POST":  
        emp = Employee()
        won = WonDetails()
        emp.eid = request.POST['eid']
        emp.ename = request.POST['ename']
        emp.status = request.POST['status']
        emp.start_date = datetime.strptime(request.POST['start_date'], "%Y/%m/%d").date()
        emp.end_date = datetime.strptime(request.POST['end_date'], "%Y/%m/%d").date()
        won.won_no = request.POST['won_no']
        won.won_name = request.POST['won_name']
        emp.won = won
        won.save()
        emp.save()
    return render(request,'index.html',{})  
def show(request):  
    employees = Employee.objects.all()  
    return render(request,"show.html",{'employees':employees})  
def edit(request, id):  
    employee = Employee.objects.get(eid=id)  
    return render(request,'edit.html', {'employee':employee})  
def update(request, id):  
    emp = Employee.objects.get(eid=id)  
    if request.method == "POST":  
        emp.eid = request.POST['eid']
        emp.ename = request.POST['ename']
        emp.status = request.POST['status']
        emp.start_date = datetime.strptime(request.POST['start_date'], "%Y/%m/%d").date()
        emp.end_date = datetime.strptime(request.POST['end_date'], "%Y/%m/%d").date()
        emp.won.won_no = request.POST['won_no']
        emp.won.won_name = request.POST['won_name']
        print "*************"
        print emp.won.won_name
        emp.won.save()
        emp.save()
    return render(request, 'edit.html', {'employee': emp})  
def destroy(request, id):  
    employee = Employee.objects.get(eid=id)  
    employee.delete()  
    return redirect("/show")  

employee/employee_mgmt/empapp/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{employee.eid}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
    </div>  
  </div>  
     
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Status:</label>  
    <div class="col-sm-4">  
        <input type="text" name="status" id="id_status" required  value="{{ employee.status }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Start Date:</label>  
    <div class="col-sm-4">  
        <input type="text" name="start_date" id="id_start_date" required  value='{{ employee.start_date|date:"Y/m/d" }}' />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">End Date:</label>  
    <div class="col-sm-4">  
        <input type="text" name="end_date" id="id_end_date" required  value='{{ employee.end_date|date:"Y/m/d" }}' />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">WON Number:</label>  
    <div class="col-sm-4">  
        <input type="text" name="won_no" id="id_won_no" required  value="{{ employee.won.won_no }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">WON Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="won_name" id="id_won_name" required  value="{{ employee.won.won_name }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

employee/employee_mgmt/empapp/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Status:</label>  
    <div class="col-sm-4">  
        <input type="text" name="status" id="id_status" required  value="{{ employee.status }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Start Date:</label>  
    <div class="col-sm-4">  
        <input type="text" name="start_date" id="id_start_date" required  value="{{ employee.start_date }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">End Date:</label>  
    <div class="col-sm-4">  
        <input type="text" name="end_date" id="id_end_date" required  value="{{ employee.end_date }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Won Number:</label>  
    <div class="col-sm-4">  
        <input type="text" name="won_no" id="id_won_no" required  value="{{ employee.won.won_no }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Won Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="won_name" id="id_won_name" required  value="{{ employee.won.won_name }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

employee/employee_mgmt/empapp/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Employee Records</title>  
     {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Employee ID</th>  
        <th>Employee Name</th>  
        <th>Employee Status</th>  
        <th> Start Date</th>  
        <th> End Date</th>  
        <th> Won Number</th>  
        <th> Won Name</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for employee in employees %}  
    <tr>  
        <td>{{ employee.eid }}</td>  
        <td>{{ employee.ename }}</td>  
        <td>{{ employee.status }}</td>  
        <td>{{ employee.start_date }}</td>  
        <td>{{ employee.end_date }}</td>  
        <td>{{ employee.won.won_no }}</td>  
        <td>{{ employee.won.won_name }}</td>  
        <td>  
            <a href="/edit/{{ employee.eid }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ employee.eid }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  